//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.11 at 11:05:40 AM CET 
//


package net.opengis.wmts._1;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.opengis.net/wmts/1.0}GetTile"/&gt;
 *         &lt;element name="J" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/&gt;
 *         &lt;element name="I" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/&gt;
 *         &lt;element name="InfoFormat" type="{http://www.opengis.net/ows/1.1}MimeType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="service" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="WMTS" /&gt;
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1.0.0" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getTile",
    "j",
    "i",
    "infoFormat"
})
@XmlRootElement(name = "GetFeatureInfo")
public class GetFeatureInfo {

    @XmlElement(name = "GetTile", required = true)
    protected GetTile getTile;
    @XmlElement(name = "J", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger j;
    @XmlElement(name = "I", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger i;
    @XmlElement(name = "InfoFormat", required = true)
    protected String infoFormat;
    @XmlAttribute(name = "service", required = true)
    protected String service;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * The corresponding GetTile request parameters
     * 
     * @return
     *     possible object is
     *     {@link GetTile }
     *     
     */
    public GetTile getGetTile() {
        return getTile;
    }

    /**
     * Sets the value of the getTile property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetTile }
     *     
     */
    public void setGetTile(GetTile value) {
        this.getTile = value;
    }

    public boolean isSetGetTile() {
        return (this.getTile!= null);
    }

    /**
     * Gets the value of the j property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getJ() {
        return j;
    }

    /**
     * Sets the value of the j property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setJ(BigInteger value) {
        this.j = value;
    }

    public boolean isSetJ() {
        return (this.j!= null);
    }

    /**
     * Gets the value of the i property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getI() {
        return i;
    }

    /**
     * Sets the value of the i property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setI(BigInteger value) {
        this.i = value;
    }

    public boolean isSetI() {
        return (this.i!= null);
    }

    /**
     * Gets the value of the infoFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfoFormat() {
        return infoFormat;
    }

    /**
     * Sets the value of the infoFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfoFormat(String value) {
        this.infoFormat = value;
    }

    public boolean isSetInfoFormat() {
        return (this.infoFormat!= null);
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getService() {
        if (service == null) {
            return "WMTS";
        } else {
            return service;
        }
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setService(String value) {
        this.service = value;
    }

    public boolean isSetService() {
        return (this.service!= null);
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    public boolean isSetVersion() {
        return (this.version!= null);
    }

}
