//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.27 at 02:31:50 PM CET 
//


package net.opengis.wmts._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import net.opengis.ows._1.DatasetDescriptionSummaryBaseType;


/**
 * <p>Java class for LayerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LayerType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengis.net/ows/1.1}DatasetDescriptionSummaryBaseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.opengis.net/wmts/1.0}Style" maxOccurs="unbounded"/&gt;
 *         &lt;element name="Format" type="{http://www.opengis.net/ows/1.1}MimeType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="InfoFormat" type="{http://www.opengis.net/ows/1.1}MimeType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.opengis.net/wmts/1.0}Dimension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.opengis.net/wmts/1.0}TileMatrixSetLink" maxOccurs="unbounded"/&gt;
 *         &lt;element name="ResourceURL" type="{http://www.opengis.net/wmts/1.0}URLTemplateType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LayerType", propOrder = {
    "style",
    "format",
    "infoFormat",
    "dimension",
    "tileMatrixSetLink",
    "resourceURL"
})
public class LayerType
    extends DatasetDescriptionSummaryBaseType
{

    @XmlElement(name = "Style", required = true)
    protected List<Style> style;
    @XmlElement(name = "Format", required = true)
    protected List<String> format;
    @XmlElement(name = "InfoFormat")
    protected List<String> infoFormat;
    @XmlElement(name = "Dimension")
    protected List<Dimension> dimension;
    @XmlElement(name = "TileMatrixSetLink", required = true)
    protected List<TileMatrixSetLink> tileMatrixSetLink;
    @XmlElement(name = "ResourceURL")
    protected List<URLTemplateType> resourceURL;

    /**
     * Metadata about the styles of this layer Gets the value of the style property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the style property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStyle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Style }
     * 
     * 
     */
    public List<Style> getStyle() {
        if (style == null) {
            style = new ArrayList<Style>();
        }
        return this.style;
    }

    public boolean isSetStyle() {
        return ((this.style!= null)&&(!this.style.isEmpty()));
    }

    public void unsetStyle() {
        this.style = null;
    }

    /**
     * Gets the value of the format property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the format property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFormat() {
        if (format == null) {
            format = new ArrayList<String>();
        }
        return this.format;
    }

    public boolean isSetFormat() {
        return ((this.format!= null)&&(!this.format.isEmpty()));
    }

    public void unsetFormat() {
        this.format = null;
    }

    /**
     * Gets the value of the infoFormat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the infoFormat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInfoFormat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getInfoFormat() {
        if (infoFormat == null) {
            infoFormat = new ArrayList<String>();
        }
        return this.infoFormat;
    }

    public boolean isSetInfoFormat() {
        return ((this.infoFormat!= null)&&(!this.infoFormat.isEmpty()));
    }

    public void unsetInfoFormat() {
        this.infoFormat = null;
    }

    /**
     * Extra dimensions for a tile and FeatureInfo requests.Gets the value of the dimension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dimension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDimension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Dimension }
     * 
     * 
     */
    public List<Dimension> getDimension() {
        if (dimension == null) {
            dimension = new ArrayList<Dimension>();
        }
        return this.dimension;
    }

    public boolean isSetDimension() {
        return ((this.dimension!= null)&&(!this.dimension.isEmpty()));
    }

    public void unsetDimension() {
        this.dimension = null;
    }

    /**
     * Reference to a tileMatrixSet and limits Gets the value of the tileMatrixSetLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tileMatrixSetLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTileMatrixSetLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TileMatrixSetLink }
     * 
     * 
     */
    public List<TileMatrixSetLink> getTileMatrixSetLink() {
        if (tileMatrixSetLink == null) {
            tileMatrixSetLink = new ArrayList<TileMatrixSetLink>();
        }
        return this.tileMatrixSetLink;
    }

    public boolean isSetTileMatrixSetLink() {
        return ((this.tileMatrixSetLink!= null)&&(!this.tileMatrixSetLink.isEmpty()));
    }

    public void unsetTileMatrixSetLink() {
        this.tileMatrixSetLink = null;
    }

    /**
     * Gets the value of the resourceURL property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourceURL property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourceURL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link URLTemplateType }
     * 
     * 
     */
    public List<URLTemplateType> getResourceURL() {
        if (resourceURL == null) {
            resourceURL = new ArrayList<URLTemplateType>();
        }
        return this.resourceURL;
    }

    public boolean isSetResourceURL() {
        return ((this.resourceURL!= null)&&(!this.resourceURL.isEmpty()));
    }

    public void unsetResourceURL() {
        this.resourceURL = null;
    }

}
