//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.11 at 11:05:40 AM CET 
//


package net.opengis.wmts._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import net.opengis.ows._1.BoundingBoxType;
import net.opengis.ows._1.CodeType;
import net.opengis.ows._1.DescriptionType;
import net.opengis.ows._1.WGS84BoundingBoxType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengis.net/ows/1.1}DescriptionType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.opengis.net/ows/1.1}Identifier"/&gt;
 *         &lt;element ref="{http://www.opengis.net/ows/1.1}BoundingBox" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.opengis.net/ows/1.1}SupportedCRS"/&gt;
 *         &lt;element name="WellKnownScaleSet" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.opengis.net/wmts/1.0}TileMatrix" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "identifier",
    "boundingBox",
    "supportedCRS",
    "wellKnownScaleSet",
    "tileMatrix"
})
@XmlRootElement(name = "TileMatrixSet")
public class TileMatrixSet
    extends DescriptionType
{

    @XmlElement(name = "Identifier", namespace = "http://www.opengis.net/ows/1.1", required = true)
    protected CodeType identifier;
    @XmlElementRef(name = "BoundingBox", namespace = "http://www.opengis.net/ows/1.1", type = JAXBElement.class)
    protected JAXBElement<? extends BoundingBoxType> boundingBox;
    @XmlElement(name = "SupportedCRS", namespace = "http://www.opengis.net/ows/1.1", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String supportedCRS;
    @XmlElement(name = "WellKnownScaleSet")
    @XmlSchemaType(name = "anyURI")
    protected String wellKnownScaleSet;
    @XmlElement(name = "TileMatrix", required = true)
    protected List<TileMatrix> tileMatrix;

    /**
     * Tile matrix set identifier
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setIdentifier(CodeType value) {
        this.identifier = value;
    }

    public boolean isSetIdentifier() {
        return (this.identifier!= null);
    }

    /**
     * 
     * 									Minimum bounding rectangle surrounding 
     * 									the visible layer presented by this tile matrix 
     * 									set, in the supported CRS 
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BoundingBoxType }{@code >}
     *     {@link JAXBElement }{@code <}{@link WGS84BoundingBoxType }{@code >}
     *     
     */
    public JAXBElement<? extends BoundingBoxType> getBoundingBox() {
        return boundingBox;
    }

    /**
     * Sets the value of the boundingBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BoundingBoxType }{@code >}
     *     {@link JAXBElement }{@code <}{@link WGS84BoundingBoxType }{@code >}
     *     
     */
    public void setBoundingBox(JAXBElement<? extends BoundingBoxType> value) {
        this.boundingBox = value;
    }

    public boolean isSetBoundingBox() {
        return (this.boundingBox!= null);
    }

    /**
     * Reference to one coordinate reference 
     * 								system (CRS).
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupportedCRS() {
        return supportedCRS;
    }

    /**
     * Sets the value of the supportedCRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupportedCRS(String value) {
        this.supportedCRS = value;
    }

    public boolean isSetSupportedCRS() {
        return (this.supportedCRS!= null);
    }

    /**
     * Gets the value of the wellKnownScaleSet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWellKnownScaleSet() {
        return wellKnownScaleSet;
    }

    /**
     * Sets the value of the wellKnownScaleSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWellKnownScaleSet(String value) {
        this.wellKnownScaleSet = value;
    }

    public boolean isSetWellKnownScaleSet() {
        return (this.wellKnownScaleSet!= null);
    }

    /**
     * Describes a scale level and its tile matrix.Gets the value of the tileMatrix property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tileMatrix property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTileMatrix().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TileMatrix }
     * 
     * 
     */
    public List<TileMatrix> getTileMatrix() {
        if (tileMatrix == null) {
            tileMatrix = new ArrayList<TileMatrix>();
        }
        return this.tileMatrix;
    }

    public boolean isSetTileMatrix() {
        return ((this.tileMatrix!= null)&&(!this.tileMatrix.isEmpty()));
    }

    public void unsetTileMatrix() {
        this.tileMatrix = null;
    }

}
