//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.11 at 11:05:40 AM CET 
//


package net.opengis.gml.v_3_1_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TopoPointPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TopoPointPropertyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.opengis.net/gml}TopoPoint"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TopoPointPropertyType", propOrder = {
    "topoPoint"
})
public class TopoPointPropertyType {

    @XmlElement(name = "TopoPoint", required = true)
    protected TopoPointType topoPoint;

    /**
     * Gets the value of the topoPoint property.
     * 
     * @return
     *     possible object is
     *     {@link TopoPointType }
     *     
     */
    public TopoPointType getTopoPoint() {
        return topoPoint;
    }

    /**
     * Sets the value of the topoPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link TopoPointType }
     *     
     */
    public void setTopoPoint(TopoPointType value) {
        this.topoPoint = value;
    }

    public boolean isSetTopoPoint() {
        return (this.topoPoint!= null);
    }

}
