//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.11 at 11:05:40 AM CET 
//


package net.opengis.gml.v_3_1_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TopoVolumePropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TopoVolumePropertyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.opengis.net/gml}TopoVolume"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TopoVolumePropertyType", propOrder = {
    "topoVolume"
})
public class TopoVolumePropertyType {

    @XmlElement(name = "TopoVolume", required = true)
    protected TopoVolumeType topoVolume;

    /**
     * Gets the value of the topoVolume property.
     * 
     * @return
     *     possible object is
     *     {@link TopoVolumeType }
     *     
     */
    public TopoVolumeType getTopoVolume() {
        return topoVolume;
    }

    /**
     * Sets the value of the topoVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link TopoVolumeType }
     *     
     */
    public void setTopoVolume(TopoVolumeType value) {
        this.topoVolume = value;
    }

    public boolean isSetTopoVolume() {
        return (this.topoVolume!= null);
    }

}
