//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.27 at 02:31:50 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/2001/SMIL20/Language")
package org.w3.smil.v_2_0.language;
