//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.11 at 11:05:40 AM CET 
//


package org.w3.smil.v_2_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fillDefaultType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="fillDefaultType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="remove"/&gt;
 *     &lt;enumeration value="freeze"/&gt;
 *     &lt;enumeration value="hold"/&gt;
 *     &lt;enumeration value="auto"/&gt;
 *     &lt;enumeration value="inherit"/&gt;
 *     &lt;enumeration value="transition"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "fillDefaultType")
@XmlEnum
public enum FillDefaultType {

    @XmlEnumValue("remove")
    REMOVE("remove"),
    @XmlEnumValue("freeze")
    FREEZE("freeze"),
    @XmlEnumValue("hold")
    HOLD("hold"),
    @XmlEnumValue("auto")
    AUTO("auto"),
    @XmlEnumValue("inherit")
    INHERIT("inherit"),
    @XmlEnumValue("transition")
    TRANSITION("transition");
    private final String value;

    FillDefaultType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FillDefaultType fromValue(String v) {
        for (FillDefaultType c: FillDefaultType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
